### ISSUE TITLE
Blank screen after blessing new snapshot in MacOS 11.1

### ISSUE THREAD

**Issue by jamespurnama1** [dakanji/RefindPlus#12]
**Description**
Not sure if it's a bug or an error on my end. RefindPlus shows a blank screen after blessing a new snapshot of the volume. Before modifying this, RefindPlus works as intended. The blank screen is shown after the apple logo.

**To Reproduce**
1. Boot to recovery
2. Create a custom snapshot through `bless --folder /Volumes/osvolume/System/Library/CoreServices --bootefi --create-snapshot`
3. Reboot

**Environment**
 - RefindPlus Version: [v0.12.0.M]
 - OS: [MacOS 11.1]
 - Hardware: Macbook Pro 15,1 (with T2 chip)

**Additional context**
Tried to re-bless `refind_x64.efi` but the problem still persists.
[`refind.conf`](https://github.com/dakanji/RefindPlus/files/5747709/refind.conf.txt)
[log when RefindPlus is working](https://github.com/dakanji/RefindPlus/files/5747700/20x21c1127.log)
[log after blessing a new snapshot](https://github.com/dakanji/RefindPlus/files/5747703/20x28k4123.log)

**Comment by dakanji** [comment]
Not so sure your issue is related to Big Sur since from looking at your logs, the mentioned change to Big Sur is not the only difference between both instances. That is, it is not a like for like comparison with the only difference being the Big Sur change.

The second failing instance has some Linux items that are not in the first and RefindPlus appears to be crashing when trying to process one of the manual stanzas for one of the Linux instances. Perhaps misconfigured or not set up correctly?
