### ISSUE TITLE
Want to add Ventoy in showtools

### ISSUE THREAD

**Issue by 1457384613gh** [dakanji/RefindPlus#165]
## What is Ventoy?
https://www.ventoy.net/en/index.html
## How to achieve it?
Refer to the codes of the tool called `windows_recovery`
## What will it look like？
![add_ventoy](https://github.com/dakanji/RefindPlus/assets/69227436/4ba167c0-d62a-4d5b-9bb3-ef883a686714)
## Text of the configuration file
`showtools ..., ..., ..., ventoy`
`ventoy_files VTOYEFI:/EFI/BOOT/BOOTX64.EFI`
## tool_ventoy.png
![tool_ventoy](https://github.com/dakanji/RefindPlus/assets/69227436/29ddf42d-116e-4d4e-a14e-9360f87c282f)

### Background Information

https://www.ventoy.net/en/index.html

**Comment by dakanji** [comment]
Hi, 

Seems what you meant to say is that you want Ventoy to be included as a supported tool that can be added in the tools list.

Your posts are usually very unclear and maybe try to actually explain things as opposed to just posting confusing links and screenshots. You have also not taken time to actually explain what this brings to the table and why it might be a good idea. 

I can see some potential benefits but not sure whether this should not be requested upstream in rEFInd instead.
Let me see what @startergo & @joevt think

**Comment by dakanji** [comment]
> If you happen to like/dislike ...

Important this is not liking stuff but on how relevant it is and determining relevance is based on information you provide as i don't know much about this item.

I have taken a quick look at it seems interesting but few questions.
1. Since it is on a bootable USB, does it not already show up as a bootable USB without needing to make it a tool?
2. Have you implemented it as a tool somewhere already?

**Comment by dakanji** [comment]
Thanks but did not understand fully.

I meant that when you plug in the Ventoy USB stick and start RefindPlus, does this not show up without you doing anything extra? I would have expected this would be the case .... is it not?

**Comment by dakanji** [comment]
> Many big icons

I see. 

So even if added as a tool, additional steps will be needed to stop the components showing on the first row.

**Comment by joevt** [comment]
bootx64.efi needs to be given a unique name like ventoy.efi for RefindPlus to be able to identify it.

The RefindPlus config file needs a section for adding arbitrary tools - maybe a tool name followed by a list of possible names or patterns: `ventoy = ventoy.efi, ventoy*.efi`.

Another option is to add the tool as a menu option but have a `istool` setting so that the menu option appears in the tool list instead of the main menu list.

Anything added as a tool should automatically not be added as a boot option (like how RecoveryHD options only appear in the tools list).

**Comment by dakanji** [comment]
> The RefindPlus config file needs a section for adding arbitrary tools

You have mentioned this before. Will make a note to look into this.

For now, I have actually already more or less knocked something together for Ventoy as it just needed duplicating the Windows Recovery code as @1457384613gh pointed out.

Will finalise presently.

**Comment by dakanji** [comment]
Please try the attached test build: [X317-BOOTx64.zip](https://github.com/dakanji/RefindPlus/files/11964615/X317-BOOTx64.zip)

You should be able to just add `ventoy` to the tools list and it should have a `tool_ventoy` icon if present

**Comment by dakanji** [comment]
Test both. First try `showtools ..., ..., ..., ventoy` alone then add `ventoy_files` later

**Comment by dakanji** [comment]
Thanks. Will take a closer look later.

**Comment by dakanji** [comment]
The log you shared is from a run where "ventoy" was not in the showtools list

**Comment by dakanji** [comment]
i know but while you may have added the item there, it is not making it into the ShowTools variable as it should.
Hence the request to take out all the complicated moving parts and run the test on a standard configuration.
Could be that something is overriding things elsewhere ... possible when using 1,000 different config files.

**Comment by dakanji** [comment]
> There is only one showtools

Your log says that is not the case.
The showtools list proceesed in your log was:
`shell,memtest,gdisk,,apple_recovery,windows_recovery,mok_tool,about,hidden_tags,shutdown,reboot,firmware,fwupdate`

Obviously no relationship to what you showed.

So please set up a normal instance and test with this.

**Comment by dakanji** [comment]
Yes. Will decide and finalise sometime next week.

**Comment by dakanji** [comment]
> Will decide and finalise sometime next week.

The second option will be implemented.
That is, Ventoy will be handled as a loader (first row) and not by a new tool (second row).

A new config option, `handle_ventoy`, must be active to enable special handling.
Otherwise, nothing special will be done and things will work as they currently do.

An `os_ventoy` icon will be shown if present in the icons folder and `handle_ventoy` is set.
Otherwise, the `uknown` or `dummy` images will be used.

A `HotFix` build for v0.14.0.AA is planned to address a few issues that have cropped up
This feature will be included in that build; which will be added to the v0.14.0.AA release tag when completed.

**Comment by dakanji** [comment]
> A new config option, handle_ventoy, must be active to enable special handling.

This requirement, previously not in an actual release, has been dropped in Commit 1d74f2cf056d91ffd63ae160a563867dfa10712c and would not be in the feature when introduced in v0.14.0.AB

UPDATE:
Reintroduced in Commit a2a035115540259b74b9b9c550b03c5940f96c0a and would appear in v0.14.0.AC

SUMMARY:
` handle_ventoy` was in pre-release code but not included with feature introduced in v0.14.0.AB. Now added for v0.14.0.AC
