### ISSUE TITLE
OC loads in text mode despite "Restore Graphics Mode ...Success"

### ISSUE THREAD

**Issue by startergo** [dakanji/RefindPlus#29]
**Describe the bug**
OC loads in text mode instead of graphics mode as usual.
**To Reproduce**
Steps to reproduce the behaviour:
Boot RP-->OC

**Expected behaviour**
Graphical boot picker to load

**Environment:**
 - RefindPlus Version : 0.13.1.AC 
 - Hardware
   * Computer         :  MacPro 5,1
   * GPU Model        : RX 580
   * GPU Port         : DP
   * GPU Flash        : NO
 - Affected OS        : OC

**Log and Config Files**
[21f08z5028.log.zip](https://github.com/dakanji/RefindPlus/files/6104847/21f08z5028.log.zip)

**Comment by dakanji** [comment]
Not an issue as extending the default behaviour of using text screen mode for EFI loaders to include OC (which was previously specifically excluded).

This has some minor clean up to do to finalise.

**Comment by startergo** [comment]
Actually this is not related to RP, but OC because even booting directly OC it boots in text mode.

**Comment by startergo** [comment]
I had to update OcBinaryData and now graphics mode works. No need to revert the code.

**Comment by dakanji** [comment]
> Actually this is not related to RP

Yes and you you had set RP to Text Only. 
What I meant was that this revision was already in progress anyway and this was going to be how things work anyway.

**Comment by startergo** [comment]
> Yes and you had set RP to Text Only.

No it always was in OpenCanopy mode. It switched to text mode because the OC binary data had to be updated, not because of RP as I thought initially.

**Comment by dakanji** [comment]
I know ... that's what the "Yes" referred to in my answer.

Regardless though, you had RP in text mode and previously, RP would have still switched to graphics mode when booting into OC.  This no longer happens which was what I was explaining.

**Comment by startergo** [comment]
> you had RP in text mode

Oh I see. This means actually internally not that I specifically instructed it to switch to text mode.

**Comment by dakanji** [comment]
The `Restore Graphics Mode ...Success` message was misleading as it actually meant the `SwitchToGraphicsAndClear` function was run successfully. The message only showed up when the screen was previously in text mode but running that function does not mean that a switch actually happened.

What was happening was that RP was it text mode and therefore each time the function was called, the message was shown but nothing was switched.

As to how RP got into text mode, this happens when either:
- Graphics mode could not be set
  * This event is logged and does not appear in your log so can be ruled out.
- The `text-only` token is active
  * That it, the user specifically switched it on

**Comment by dakanji** [comment]
Could be the 3rd option.
