### ISSUE TITLE
RefindPlus stalls after scanning drives

### ISSUE THREAD

**Issue by vhalkola** [dakanji/RefindPlus#40]
RefindPlus stalls on HP Z440 after scanning drives, showing only the banner and otherwise a blank light grey sceen.

Steps to reproduce the behaviour:
1. Boot RefindPlus

The expected behaviour would be to show the boot alternatives and tools.

Environment:
 - RefindPlus Version : 0.13.1.AB
 - Hardware
   * Computer         : HP Z440 Xeon E5-1660 v4, 32 GB 2400MHz ECC DDR4, latest UEFI BIOS version (11/03/2020), all security features turned off
   * GPU Model        : Nvidia GeForce GTX 645 OEM
   * GPU Port          : DP
   * GPU Flash        : no
 - Affected OS        : issue prior to loading any OS; installed operating systems Win 10 and Manjaro.

Log file from the debug version and configuration file attached.

Original Refind also stalls similarly. There were no issues with my old HP computer (HP Compaq 8200 Elite) with the same GPU and operating systems. I also have a Mac Pro 3,1 that has no issues booting with RefindPlus. 

[21f24p2433.log](https://github.com/dakanji/RefindPlus/files/6197507/21f24p2433.log)

[config.txt](https://github.com/dakanji/RefindPlus/files/6197511/config.txt)

**Comment by dakanji** [comment]
Can you try the v0.13.2 version of rEFInd (which has logging), set `log_level` to 4 in the config and share the log?

Also, update your ext4 driver with the one from that new version as some issues were fixed recently.

**Comment by vhalkola** [comment]
> Can you try the v0.13.2 version of rEFInd (which has logging), set `log_level` to 4 in the config and share the log?

It stalls at the same phase, but now there is more information. If I interpret the log correctly, it tries to scan a Windows data partition for bootloaders and stalls there. The SATA configuration is SATA0: 1TB NTFS single partition, SATA1 500GB NTFS single partition, SATA2: ESP, Win10 recovery, 16MB MS reserved partition, 300GB NTFS Win10 and 200GB ext4 Linux

[refind.log](https://github.com/dakanji/RefindPlus/files/6199692/refind.log)
 
> Also, update your ext4 driver with the one from that new version as some issues were fixed recently.

**Comment by dakanji** [comment]
> looks like the driver was never used for anything, as the ext4 filesystem was never read.

The hang is caused by memory management issues which the https://github.com/dakanji/RefindPlus/issues/34 fix addresses and was implemented upstream as well. Such issues can be triggered just by loading the driver Not sure this one will, but best to use fixed version.

 > It stalls at the same phase, but now there is more information. If I interpret the log correctly, it tries to scan a Windows data partition for bootloaders and stalls there.

The last logged item is this in `ScanLoaderDir` which is quite a messy function:
https://github.com/dakanji/rEFInd/blob/6481639f37dcdbed494c00b34a6e6796312049da/refind/scan.c#L911

It also has a note about some ignored errors (doesn't seem something that would cause a hang though):
https://github.com/dakanji/rEFInd/blob/6481639f37dcdbed494c00b34a6e6796312049da/refind/scan.c#L966-L969

Anyway, done a few memory management fixes since the last release such as the driver fix mentioned earlier. Part of that was in this function although I don't think the potential fundamentals were fixed and needs a second look.

You can try [this build](https//dakanji.com/X111-BOOTx64.zip) of the latest code base and see what happens.

if it works, then the tweaks helped and I will pass them on upstream. If not, we will need to refer the issue upstream.

**Comment by vhalkola** [comment]
> You can try [this build](https://dakanji.com/X111-BOOTx64.zip) of the latest code base and see what happens.
> 
> if it works, then the tweaks helped and I will pass them on upstream. If not, we will need to refer the issue upstream.

This version stalls before the banner and grey background get drawn.
[21f25a1739.log](https://github.com/dakanji/RefindPlus/files/6200832/21f25a1739.log)

**Comment by dakanji** [comment]
I see.

Please [try this one](https://dakanji.com/X112-BOOTx64.zip) and post the log.
No fixes there, just additional logging.

**Comment by vhalkola** [comment]
Here's the extended log:

[21f25n2250.log](https://github.com/dakanji/RefindPlus/files/6203935/21f25n2250.log)

**Comment by dakanji** [comment]
Thanks.

Please post the log from [this one](https://dakanji.com/X113-BOOTx64.zip) which has further debug prints

**Comment by vhalkola** [comment]
> Here's the extended log:
> 
> [21f25n2250.log](https://github.com/dakanji/RefindPlus/files/6203935/21f25n2250.log)

After further modification of BIOS settings (as listed in config.txt)
[config.txt](https://github.com/dakanji/RefindPlus/files/6205021/config.txt)
the X112 build proceeded a bit further before stalling:
[21f25z2505.log](https://github.com/dakanji/RefindPlus/files/6205029/21f25z2505.log)

**Comment by vhalkola** [comment]
> Thanks.
> 
> Please post the log from [this one](https://dakanji.com/X113-BOOTx64.zip) which has further debug prints

With the BIOS settings kept as in the list in my previous post.

[21f25z4020.log](https://github.com/dakanji/RefindPlus/files/6205064/21f25z4020.log)

**Comment by dakanji** [comment]
Something just struck me.

What happens if you just press any key when it is stalled?

It might proceed after this.

**Comment by vhalkola** [comment]
> Something just struck me.
> 
> What happens if you just press any key when it is stalled?
> 
> It might proceed after this.

No effect, as matter of fact, the keyboard becomes completely unresponsive and only power button has any effect at all. In the earlier cases when the banner and the background got drawn it was possible to reboot by pressing Ctrl-Alt-Del.

**Comment by dakanji** [comment]
I see.

The last log shows the banner was drawn and that it went past the previous failure point.
There was no other change apart from the logging which should not affect such.

Points to a memory allocation conflict or some other memory management issue somewhere.
Unfortunately, no idea at this point where that is if this is indeed the case as automated static analysis of the code is not flagging anything.

Problem with these is that the point where the failure happens is not necessarily where the issue lies (usually not actually).

if you have a Sourceforge account, please raise this upstream for possible insight by posting in the [upstream discussion forum](https://sourceforge.net/p/refind/discussion/general/).

Attach the rEFInd log file from before.

**Comment by dakanji** [comment]
Hi,

Haven't noticed a report upstream but in any case, can you try running RefindPlus with the `text_renderer` token activated in the config before you make a report?

**Comment by vhalkola** [comment]
I'm terribly sorry, I've been occupied with other matters. I posted the issue in the rEFInd discussion on SourceForge today. The state of `text_renderer` token does not seem to affect anything, the process stalls at the same stage.
[21f30p2412.log](https://github.com/dakanji/RefindPlus/files/6228907/21f30p2412.log)

**Comment by vhalkola** [comment]
Alright, with help from Roderick Smith I was able to pinpoint the problem. What goes wrong is indeed the scanning phase, in this case scanning for bootloaders on NTFS volumes. As a workaround, I've excluded all NTFS partitions from the scan. The robust approach would probably be to refuse all drivers not loaded by rEFInd/RefindPlus itself, as the problem is possibly caused by somewhat faulty NTFS driver in HP's UEFI.

**Comment by vhalkola** [comment]
Further digging into the matter reveals that HP indeed provides an NTFS driver bundled into UEFI, and it's obviously this driver that is to blame. Reading NTFS volumes is possible from an EFI shell, but causes stall if done from BIOS or during rEFInd startup.

**Comment by dakanji** [comment]
Thanks. 

Will shut this down and keep an eye on developments upstream.
